# Generated by Django 4.0.4 on 2022-06-10 04:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('Project_Name', models.CharField(max_length=200)),
                ('Description', models.TextField(blank=True, null=True)),
                ('demo_link', models.CharField(max_length=1000)),
                ('source_link', models.CharField(max_length=1000)),
                ('vote_total', models.IntegerField(default=0)),
                ('vote_ratio', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
