# Generated by Django 4.0.4 on 2022-06-10 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectweb', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='demo_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='source_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
